apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-test
  labels:
    app: java-docker-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-docker-test
  template:
    metadata:
      labels:
        app: java-docker-test
    spec:
      containers:
      - name: java-app
        image: 18621759267/devopsapp:latest  # 替换为你的实际镜像地址
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
