apiVersion: v1
kind: Service
metadata:
  name: java-docker-test-service
spec:
  type: LoadBalancer  # 如果使用内部访问可改为 ClusterIP
  selector:
    app: java-docker-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
